### PR TITLE
Improve the tail plugin

### PR DESCRIPTION
**Pull request by guillaume-eb**
Change the default number of lines to all.
Switch the number of lines from a parameter to an option.
Copied docker logs documentation.

### CODE REVIEW

**Comment by guillaume-eb** [comment]
good point @nickwilliams-eventbrite. I can fix the documentation.
I can also a `bay logs` command that would behave like `docker logs`, what do you think?

**Comment by nickwilliams-eventbrite** [comment]
>good point @nickwilliams-eventbrite. I can fix the documentation.
>I can also a `bay logs` command that would behave like `docker logs`, what do you think?

I love the idea of a `bay logs` command and fully support it. Additionally, as I said before, I think the proper direction is to make it so that `bay tail --all ...` replaces `bay tail ... all`.

**Comment by guillaume-eb** [comment]
@nickwilliams-eventbrite how does it look now?

**Comment by bar** [comment]
so `bay tail` and `bay logs` mean different things to me

`bay tail` should output the container's stdout
`bay logs` should output the container's (service actually) logs

but... `bay logs` shouldn't be (that much) necessary if all service containers were to write and expose logs to `~/eventbrite/docker-dev/volumes/logs/eventbrite/{service_name}_service.log` like most of them do

**Comment by guillaume-eb** [comment]
What about now?
You can do:
- `bay tail xyz`
- `bay tail -f xyz`
- `bay tail --all xyz`
- `bay tail xyz 20`
- `bay logs xyz`
- `bay logs -f xyz`

**Comment by nickwilliams-eventbrite** [comment]
But, you still have some kind of failing check, so be sure to fix that.

**Pull request merged**
